baseURL = 'https://practice-of-information.netlify.app/'
languageCode = 'en-us'
title = 'The Practice of Information Architecture'
theme = 'shadocs'

[params]
  logo		= "images/logo.png"
  logoTouch	= "images/logoTouch.png"
  image404	= "images/404.gif"
  favicon	= "images/favicon.png"
